// Generated by gencpp from file disturbance_sources/DisturbRatioResponse.msg
// DO NOT EDIT!


#ifndef DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIORESPONSE_H
#define DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace disturbance_sources
{
template <class ContainerAllocator>
struct DisturbRatioResponse_
{
  typedef DisturbRatioResponse_<ContainerAllocator> Type;

  DisturbRatioResponse_()
    : ratio(0.0)  {
    }
  DisturbRatioResponse_(const ContainerAllocator& _alloc)
    : ratio(0.0)  {
  (void)_alloc;
    }



   typedef double _ratio_type;
  _ratio_type ratio;





  typedef boost::shared_ptr< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DisturbRatioResponse_

typedef ::disturbance_sources::DisturbRatioResponse_<std::allocator<void> > DisturbRatioResponse;

typedef boost::shared_ptr< ::disturbance_sources::DisturbRatioResponse > DisturbRatioResponsePtr;
typedef boost::shared_ptr< ::disturbance_sources::DisturbRatioResponse const> DisturbRatioResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator1> & lhs, const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ratio == rhs.ratio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator1> & lhs, const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace disturbance_sources

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a9814c2e046da76c15f5a76016fa0c1";
  }

  static const char* value(const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a9814c2e046da76ULL;
  static const uint64_t static_value2 = 0xc15f5a76016fa0c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disturbance_sources/DisturbRatioResponse";
  }

  static const char* value(const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ratio\n"
;
  }

  static const char* value(const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ratio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DisturbRatioResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disturbance_sources::DisturbRatioResponse_<ContainerAllocator>& v)
  {
    s << indent << "ratio: ";
    Printer<double>::stream(s, indent + "  ", v.ratio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIORESPONSE_H
