// Generated by gencpp from file disturbance_sources/DisturbRatio.msg
// DO NOT EDIT!


#ifndef DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIO_H
#define DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIO_H

#include <ros/service_traits.h>


#include <disturbance_sources/DisturbRatioRequest.h>
#include <disturbance_sources/DisturbRatioResponse.h>


namespace disturbance_sources
{

struct DisturbRatio
{

typedef DisturbRatioRequest Request;
typedef DisturbRatioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisturbRatio
} // namespace disturbance_sources


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::disturbance_sources::DisturbRatio > {
  static const char* value()
  {
    return "357bf3ef38c1e016d0352525c776ffa2";
  }

  static const char* value(const ::disturbance_sources::DisturbRatio&) { return value(); }
};

template<>
struct DataType< ::disturbance_sources::DisturbRatio > {
  static const char* value()
  {
    return "disturbance_sources/DisturbRatio";
  }

  static const char* value(const ::disturbance_sources::DisturbRatio&) { return value(); }
};


// service_traits::MD5Sum< ::disturbance_sources::DisturbRatioRequest> should match
// service_traits::MD5Sum< ::disturbance_sources::DisturbRatio >
template<>
struct MD5Sum< ::disturbance_sources::DisturbRatioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::disturbance_sources::DisturbRatio >::value();
  }
  static const char* value(const ::disturbance_sources::DisturbRatioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::disturbance_sources::DisturbRatioRequest> should match
// service_traits::DataType< ::disturbance_sources::DisturbRatio >
template<>
struct DataType< ::disturbance_sources::DisturbRatioRequest>
{
  static const char* value()
  {
    return DataType< ::disturbance_sources::DisturbRatio >::value();
  }
  static const char* value(const ::disturbance_sources::DisturbRatioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::disturbance_sources::DisturbRatioResponse> should match
// service_traits::MD5Sum< ::disturbance_sources::DisturbRatio >
template<>
struct MD5Sum< ::disturbance_sources::DisturbRatioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::disturbance_sources::DisturbRatio >::value();
  }
  static const char* value(const ::disturbance_sources::DisturbRatioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::disturbance_sources::DisturbRatioResponse> should match
// service_traits::DataType< ::disturbance_sources::DisturbRatio >
template<>
struct DataType< ::disturbance_sources::DisturbRatioResponse>
{
  static const char* value()
  {
    return DataType< ::disturbance_sources::DisturbRatio >::value();
  }
  static const char* value(const ::disturbance_sources::DisturbRatioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DISTURBANCE_SOURCES_MESSAGE_DISTURBRATIO_H
